## Functional enrichment analysis by clusterProfiler

parser = argparse::ArgumentParser(description = 'Script for function enrichment analysis')
parser$add_argument('-i', '--input', dest = 'input', default=NULL, help = 'Input markerGene filename which generated by Seurat workflow [default %(default)s]')
parser$add_argument('-s', '--species', dest = 'species', default=NULL, help = 'species name (Human or Mouse) [default %(default)s]')
parser$add_argument('-o', '--out', dest = 'out', default=NULL, help = 'Directory to save file [default %(default)s]')
parser$add_argument('-c', '--cluster', dest = 'cluster', default=NULL, help = 'Cluser file name to compare go enrichment [default %(default)s]')
parser$add_argument('--prefix', dest = 'prefix', default = 'sample', help = 'sample ID, will be used as output prefix and seurat object ident [default %(default)s]')

opts = parser$parse_args()
print(opts)

#################Debug#######################
# rm(list=ls())
# gc()
# opts <- list()
# opts$input <- '/ldfssz1/ST_OCEAN/USER/liaoshangfeng/Project/01.scat_debug/example/go_debug/sample_hku.szh.2.1_bin100_AllMarkers.xls'
# opts$output <- '/ldfssz1/ST_OCEAN/USER/liaoshangfeng/Project/01.scat_debug/example/go_debug/out'
# opts$species <- 'Mouse'
#############################################


### Function

#' define a enrichment function
get_go <- function(genelist, organism){
    suppressMessages(library(clusterProfiler))
    suppressMessages(library(AnnotationDbi))
    suppressMessages(library(org.Hs.eg.db))
    suppressMessages(library(org.Mm.eg.db))
    suppressMessages(library(DOSE))
    suppressMessages(library(topGO))
    if (organism == "Human"){
        ref_db <- "org.Hs.eg.db"
    } else if (organism == "Mouse"){
        ref_db <- "org.Mm.eg.db"
    }

    eg <- suppressMessages(bitr(genelist, fromType="SYMBOL", toType=c("ENTREZID","ENSEMBL"), OrgDb=ref_db))
    genelist <- eg$ENTREZID
    genelist  <- genelist[!duplicated(genelist)]
    go.BP <- enrichGO(genelist, OrgDb = ref_db, ont='BP',pAdjustMethod = 'BH',pvalueCutoff = 0.05, qvalueCutoff = 0.2, keyType = 'ENTREZID')
    return(list(go.BP, genelist))
}


#' define a function to adjust the y label of dotplot
get_wraper <- function(width) {
    function(x) {
        lapply(strwrap(x, width = width, simplify = FALSE), paste, collapse="\n")
    }
}


#' define a function to plot dotplot
get_dotplot <- function(go=NULL, showCategory=15, cluster_name=NULL, out_dir=NULL){
    suppressMessages(library(ggplot2))
    go <- go[1:showCategory,]
    go <- go[order(go$p.adjust,decreasing = T),]
    go <- go[order(go$Count,decreasing = F),]
    
    # transform GeneRation to number
    a = go$GeneRatio
    options(stringsAsFactors = F)
    a <- data.frame(name=a)
    
    x <- apply(a,1,function(x) eval(parse(text=x)))
    y=factor(go$Description,levels = go$Description)
    
    p <- ggplot(go,aes(x,y))+
      scale_color_gradient(high = "blue", low = "red")+ 
      geom_point(aes(color=p.adjust,size=Count))+
      # geom_point(aes(size=GeneCount,color=-log(go$P.Value),shape=Category))
      # scale_y_discrete(labels=function(x) str_wrap(x, width=30))+
      scale_y_discrete(labels= get_wraper(35))+
      labs(color=expression(p.adjust),size="Count",x="GeneRation",y="")+
      theme_bw()+
      theme(axis.line = element_line(colour = "black"), 
            axis.text = element_text(color = "black",size = 14),
            legend.text = element_text(size = 14),legend.title=element_text(size=14),
            axis.title.x = element_text(size = 14),
            panel.grid=element_blank())+
      scale_size_continuous(range=c(4,8))
    
    # output the dotplot
    file_name <- paste(cluster_name, "dotplot.pdf", sep = "_")
    pdf(file=paste(out_dir,file_name,sep = "/"),height = 10, width = 8)
    print(p)
    while (!is.null(dev.list()))  dev.off()
    return(p)
}


#' define a function to perform enrichment 
do_enrichment <- function(opts){
    # perform enrichment for each cluster
    if (! is.null(opts$input)) {
    myData <- read.table(opts$input, header = T, row.names = 1, sep = "\t")
    # select significant genes by cutoff (p_val_adj < 0.01 & avg_log2FC > 0.1(1.2))
    # myData.sort <- myData[order(myData$p_val_adj),]
    # myData.sort <- myData.sort[myData.sort$p_val_adj < 0.05 &&  myData.sort$avg_log2FC > 0.5,]
    myData.sort <- myData[myData$p_val_adj < 0.05 &  myData$avg_log2FC > 0.5,]
    for (i in unique(myData.sort$cluster)) {
        cluster.geneList <- myData.sort$gene[myData.sort$cluster == i]
        ## This step will generate error when there are few genes.
        try({
            go <- suppressWarnings(get_go(cluster.geneList, opts$species))
            go_enrichment <- suppressMessages(go[[1]]@result)
            cluster_name <- paste("C", i, sep = "_")
            file_out <- paste(opts$out, "/", cluster_name, "_go_enrichment.csv", sep = "")
            write.csv(go_enrichment, file_out)
            get_dotplot(
                        go = go_enrichment,
                        showCategory = 15,
                        cluster_name = cluster_name,
                        out_dir = opts$out)
        }) 
    }
    } 
    
    ## compareCluster 需要提前定义参考数据库，所以需要输入生物类型
    organism = opts$species
    if (organism == "Human"){
        ref_db <- "org.Hs.eg.db"
    } else if (organism == "Mouse"){
        ref_db <- "org.Mm.eg.db"
    }


    # perform enrichment for all cluster genes
    if(! is.null(opts$cluster)){
        clusters <- read.table(opts$cluster, header = T,  check.names=FALSE)
        gc <- list()
        cl_name <- character()
        for (i in clusters[,1]) {
            cluster.geneList <- myData.sort$gene[myData.sort$cluster == i]
            try({
                go <- suppressWarnings(get_go(cluster.geneList, opts$species))
                go_enrichment <- suppressMessages(go[[1]]@result)
                cl_name <- c(cl_name, paste("C", i, sep = ""))
                gc <- c(gc,list(go[[2]]))
            })
        }
        names(gc) <- cl_name
        x <- compareCluster(gc,fun='enrichGO',OrgDb=ref_db, ont="BP")
        p <- dotplot(x)
        
        # output the dotplot
        file_out <-  "all_cluster_GO_enrichment_dotplot.pdf"
        pdf(file=paste(opts$out, "/", file_out, sep=""),height = 10, width = 12)
        print(p)
        while (!is.null(dev.list()))  dev.off()
    }
}


### Main Work flow
if ((! is.null(opts$input)) & (! is.null(opts$species)) & (!is.null(opts$out))){
    if (! file.exists(opts$out)){
        dir.create(opts$out, recursive = TRUE)}
    do_enrichment(opts) 
} else {
    parser$print_help()
    stop("You need to provide the following parameters: --input, --species, --out", call.=FALSE)
}
